
package mx.gob.edomex.icati.siicati.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CursosCEAWS", targetNamespace = "http://webservice.icati.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CursosCEAWS {


    /**
     * 
     * @return
     *     returns java.util.List<mx.gob.edomex.icati.siicati.webservice.SelectItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemsEdayos", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.GetItemsEdayos")
    @ResponseWrapper(localName = "getItemsEdayosResponse", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.GetItemsEdayosResponse")
    @Action(input = "http://webservice.icati.com/CursosCEAWS/getItemsEdayosRequest", output = "http://webservice.icati.com/CursosCEAWS/getItemsEdayosResponse")
    public List<SelectItem> getItemsEdayos();

    /**
     * 
     * @param fechaInicial
     * @param idEdayo
     * @param fechaFinal
     * @return
     *     returns mx.gob.edomex.icati.siicati.webservice.ReporteWS
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTotalCursoYAlumnosPorPeriodoCEA", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalCursoYAlumnosPorPeriodoCEA")
    @ResponseWrapper(localName = "consultaTotalCursoYAlumnosPorPeriodoCEAResponse", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalCursoYAlumnosPorPeriodoCEAResponse")
    @Action(input = "http://webservice.icati.com/CursosCEAWS/consultaTotalCursoYAlumnosPorPeriodoCEARequest", output = "http://webservice.icati.com/CursosCEAWS/consultaTotalCursoYAlumnosPorPeriodoCEAResponse")
    public ReporteWS consultaTotalCursoYAlumnosPorPeriodoCEA(
        @WebParam(name = "idEdayo", targetNamespace = "")
        Integer idEdayo,
        @WebParam(name = "fechaInicial", targetNamespace = "")
        String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "")
        String fechaFinal);

    /**
     * 
     * @param fechaInicial
     * @param tipoConsulta
     * @param fechaFinal
     * @return
     *     returns java.util.List<mx.gob.edomex.icati.siicati.webservice.ReporteWS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTotalAlumnosPorPeriodoCEA", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalAlumnosPorPeriodoCEA")
    @ResponseWrapper(localName = "consultaTotalAlumnosPorPeriodoCEAResponse", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalAlumnosPorPeriodoCEAResponse")
    @Action(input = "http://webservice.icati.com/CursosCEAWS/consultaTotalAlumnosPorPeriodoCEARequest", output = "http://webservice.icati.com/CursosCEAWS/consultaTotalAlumnosPorPeriodoCEAResponse")
    public List<ReporteWS> consultaTotalAlumnosPorPeriodoCEA(
        @WebParam(name = "tipoConsulta", targetNamespace = "")
        Integer tipoConsulta,
        @WebParam(name = "fechaInicial", targetNamespace = "")
        String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "")
        String fechaFinal);

    /**
     * 
     * @param fechaInicial
     * @param tipoConsulta
     * @param fechaFinal
     * @return
     *     returns java.util.List<mx.gob.edomex.icati.siicati.webservice.ReporteWS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTotalAlumnosPorPeriodoCAE", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalAlumnosPorPeriodoCAE")
    @ResponseWrapper(localName = "consultaTotalAlumnosPorPeriodoCAEResponse", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalAlumnosPorPeriodoCAEResponse")
    @Action(input = "http://webservice.icati.com/CursosCEAWS/consultaTotalAlumnosPorPeriodoCAERequest", output = "http://webservice.icati.com/CursosCEAWS/consultaTotalAlumnosPorPeriodoCAEResponse")
    public List<ReporteWS> consultaTotalAlumnosPorPeriodoCAE(
        @WebParam(name = "tipoConsulta", targetNamespace = "")
        Integer tipoConsulta,
        @WebParam(name = "fechaInicial", targetNamespace = "")
        String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "")
        String fechaFinal);

    /**
     * 
     * @param fechaInicial
     * @param idEdayo
     * @param fechaFinal
     * @return
     *     returns mx.gob.edomex.icati.siicati.webservice.ReporteWS
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTotalCursoYAlumnosPorPeriodoCAE", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalCursoYAlumnosPorPeriodoCAE")
    @ResponseWrapper(localName = "consultaTotalCursoYAlumnosPorPeriodoCAEResponse", targetNamespace = "http://webservice.icati.com", className = "mx.gob.edomex.icati.siicati.webservice.ConsultaTotalCursoYAlumnosPorPeriodoCAEResponse")
    @Action(input = "http://webservice.icati.com/CursosCEAWS/consultaTotalCursoYAlumnosPorPeriodoCAERequest", output = "http://webservice.icati.com/CursosCEAWS/consultaTotalCursoYAlumnosPorPeriodoCAEResponse")
    public ReporteWS consultaTotalCursoYAlumnosPorPeriodoCAE(
        @WebParam(name = "idEdayo", targetNamespace = "")
        Integer idEdayo,
        @WebParam(name = "fechaInicial", targetNamespace = "")
        String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "")
        String fechaFinal);

}
