
package mx.gob.edomex.icati.siicati.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CursosCEAWS", targetNamespace = "http://webservice.icati.com", wsdlLocation = "http://cursoscea.edomex.gob.mx/CursosCEAWS/CursosCEAWS?WSDL")
public class CursosCEAWS_Service
    extends Service
{

    private final static URL CURSOSCEAWS_WSDL_LOCATION;
    private final static WebServiceException CURSOSCEAWS_EXCEPTION;
    private final static QName CURSOSCEAWS_QNAME = new QName("http://webservice.icati.com", "CursosCEAWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://cursoscea.edomex.gob.mx/CursosCEAWS/CursosCEAWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURSOSCEAWS_WSDL_LOCATION = url;
        CURSOSCEAWS_EXCEPTION = e;
    }

    public CursosCEAWS_Service() {
        super(__getWsdlLocation(), CURSOSCEAWS_QNAME);
    }

    public CursosCEAWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURSOSCEAWS_QNAME, features);
    }

    public CursosCEAWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CURSOSCEAWS_QNAME);
    }

    public CursosCEAWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURSOSCEAWS_QNAME, features);
    }

    public CursosCEAWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CursosCEAWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CursosCEAWS
     */
    @WebEndpoint(name = "CursosCEAWSPort")
    public CursosCEAWS getCursosCEAWSPort() {
        return super.getPort(new QName("http://webservice.icati.com", "CursosCEAWSPort"), CursosCEAWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CursosCEAWS
     */
    @WebEndpoint(name = "CursosCEAWSPort")
    public CursosCEAWS getCursosCEAWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.icati.com", "CursosCEAWSPort"), CursosCEAWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURSOSCEAWS_EXCEPTION!= null) {
            throw CURSOSCEAWS_EXCEPTION;
        }
        return CURSOSCEAWS_WSDL_LOCATION;
    }

}
