package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AreaInteres generated by hbm2java
 */
public class AreaInteres  implements java.io.Serializable {


     private int idAreaInteres;
     private String nombreAreaInteres;
     private int idLineaInvestigacion;
     private Set relAreaInteresInvestigadors = new HashSet(0);

    public AreaInteres() {
    }

	
    public AreaInteres(int idAreaInteres, String nombreAreaInteres, int idLineaInvestigacion) {
        this.idAreaInteres = idAreaInteres;
        this.nombreAreaInteres = nombreAreaInteres;
        this.idLineaInvestigacion = idLineaInvestigacion;
    }
    public AreaInteres(int idAreaInteres, String nombreAreaInteres, int idLineaInvestigacion, Set relAreaInteresInvestigadors) {
       this.idAreaInteres = idAreaInteres;
       this.nombreAreaInteres = nombreAreaInteres;
       this.idLineaInvestigacion = idLineaInvestigacion;
       this.relAreaInteresInvestigadors = relAreaInteresInvestigadors;
    }
   
    public int getIdAreaInteres() {
        return this.idAreaInteres;
    }
    
    public void setIdAreaInteres(int idAreaInteres) {
        this.idAreaInteres = idAreaInteres;
    }
    public String getNombreAreaInteres() {
        return this.nombreAreaInteres;
    }
    
    public void setNombreAreaInteres(String nombreAreaInteres) {
        this.nombreAreaInteres = nombreAreaInteres;
    }
    public int getIdLineaInvestigacion() {
        return this.idLineaInvestigacion;
    }
    
    public void setIdLineaInvestigacion(int idLineaInvestigacion) {
        this.idLineaInvestigacion = idLineaInvestigacion;
    }
    public Set getRelAreaInteresInvestigadors() {
        return this.relAreaInteresInvestigadors;
    }
    
    public void setRelAreaInteresInvestigadors(Set relAreaInteresInvestigadors) {
        this.relAreaInteresInvestigadors = relAreaInteresInvestigadors;
    }




}


