package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Investigador generated by hbm2java
 */
public class Investigador  implements java.io.Serializable {


     private int idInvestigador;
     private String nombreInvestigador;
     private String apPaternoInvestigador;
     private String apMaternoInvestigador;
     private String gradoAcademico;
     private String especialidad;
     private Set relInvestigadorLineaGrupos = new HashSet(0);
     private Set relProyectoInvestigadors = new HashSet(0);
     private Set relAreaInteresInvestigadors = new HashSet(0);
     private Set tesistas = new HashSet(0);

    public Investigador() {
    }

	
    public Investigador(int idInvestigador, String nombreInvestigador, String apPaternoInvestigador, String gradoAcademico, String especialidad) {
        this.idInvestigador = idInvestigador;
        this.nombreInvestigador = nombreInvestigador;
        this.apPaternoInvestigador = apPaternoInvestigador;
        this.gradoAcademico = gradoAcademico;
        this.especialidad = especialidad;
    }
    public Investigador(int idInvestigador, String nombreInvestigador, String apPaternoInvestigador, String apMaternoInvestigador, String gradoAcademico, String especialidad, Set relInvestigadorLineaGrupos, Set relProyectoInvestigadors, Set relAreaInteresInvestigadors, Set tesistas) {
       this.idInvestigador = idInvestigador;
       this.nombreInvestigador = nombreInvestigador;
       this.apPaternoInvestigador = apPaternoInvestigador;
       this.apMaternoInvestigador = apMaternoInvestigador;
       this.gradoAcademico = gradoAcademico;
       this.especialidad = especialidad;
       this.relInvestigadorLineaGrupos = relInvestigadorLineaGrupos;
       this.relProyectoInvestigadors = relProyectoInvestigadors;
       this.relAreaInteresInvestigadors = relAreaInteresInvestigadors;
       this.tesistas = tesistas;
    }
   
    public int getIdInvestigador() {
        return this.idInvestigador;
    }
    
    public void setIdInvestigador(int idInvestigador) {
        this.idInvestigador = idInvestigador;
    }
    public String getNombreInvestigador() {
        return this.nombreInvestigador;
    }
    
    public void setNombreInvestigador(String nombreInvestigador) {
        this.nombreInvestigador = nombreInvestigador;
    }
    public String getApPaternoInvestigador() {
        return this.apPaternoInvestigador;
    }
    
    public void setApPaternoInvestigador(String apPaternoInvestigador) {
        this.apPaternoInvestigador = apPaternoInvestigador;
    }
    public String getApMaternoInvestigador() {
        return this.apMaternoInvestigador;
    }
    
    public void setApMaternoInvestigador(String apMaternoInvestigador) {
        this.apMaternoInvestigador = apMaternoInvestigador;
    }
    public String getGradoAcademico() {
        return this.gradoAcademico;
    }
    
    public void setGradoAcademico(String gradoAcademico) {
        this.gradoAcademico = gradoAcademico;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Set getRelInvestigadorLineaGrupos() {
        return this.relInvestigadorLineaGrupos;
    }
    
    public void setRelInvestigadorLineaGrupos(Set relInvestigadorLineaGrupos) {
        this.relInvestigadorLineaGrupos = relInvestigadorLineaGrupos;
    }
    public Set getRelProyectoInvestigadors() {
        return this.relProyectoInvestigadors;
    }
    
    public void setRelProyectoInvestigadors(Set relProyectoInvestigadors) {
        this.relProyectoInvestigadors = relProyectoInvestigadors;
    }
    public Set getRelAreaInteresInvestigadors() {
        return this.relAreaInteresInvestigadors;
    }
    
    public void setRelAreaInteresInvestigadors(Set relAreaInteresInvestigadors) {
        this.relAreaInteresInvestigadors = relAreaInteresInvestigadors;
    }
    public Set getTesistas() {
        return this.tesistas;
    }
    
    public void setTesistas(Set tesistas) {
        this.tesistas = tesistas;
    }




}


