package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LineaInvestigacion generated by hbm2java
 */
public class LineaInvestigacion  implements java.io.Serializable {


     private int idLineaInvestigacion;
     private String lineaInvestigacion;
     private Set relGrupoAcLineaInvs = new HashSet(0);
     private Set relInvestigadorLineaGrupos = new HashSet(0);
     private Set proyectosInvestigacions = new HashSet(0);

    public LineaInvestigacion() {
    }

	
    public LineaInvestigacion(int idLineaInvestigacion, String lineaInvestigacion) {
        this.idLineaInvestigacion = idLineaInvestigacion;
        this.lineaInvestigacion = lineaInvestigacion;
    }
    public LineaInvestigacion(int idLineaInvestigacion, String lineaInvestigacion, Set relGrupoAcLineaInvs, Set relInvestigadorLineaGrupos, Set proyectosInvestigacions) {
       this.idLineaInvestigacion = idLineaInvestigacion;
       this.lineaInvestigacion = lineaInvestigacion;
       this.relGrupoAcLineaInvs = relGrupoAcLineaInvs;
       this.relInvestigadorLineaGrupos = relInvestigadorLineaGrupos;
       this.proyectosInvestigacions = proyectosInvestigacions;
    }
   
    public int getIdLineaInvestigacion() {
        return this.idLineaInvestigacion;
    }
    
    public void setIdLineaInvestigacion(int idLineaInvestigacion) {
        this.idLineaInvestigacion = idLineaInvestigacion;
    }
    public String getLineaInvestigacion() {
        return this.lineaInvestigacion;
    }
    
    public void setLineaInvestigacion(String lineaInvestigacion) {
        this.lineaInvestigacion = lineaInvestigacion;
    }
    public Set getRelGrupoAcLineaInvs() {
        return this.relGrupoAcLineaInvs;
    }
    
    public void setRelGrupoAcLineaInvs(Set relGrupoAcLineaInvs) {
        this.relGrupoAcLineaInvs = relGrupoAcLineaInvs;
    }
    public Set getRelInvestigadorLineaGrupos() {
        return this.relInvestigadorLineaGrupos;
    }
    
    public void setRelInvestigadorLineaGrupos(Set relInvestigadorLineaGrupos) {
        this.relInvestigadorLineaGrupos = relInvestigadorLineaGrupos;
    }
    public Set getProyectosInvestigacions() {
        return this.proyectosInvestigacions;
    }
    
    public void setProyectosInvestigacions(Set proyectosInvestigacions) {
        this.proyectosInvestigacions = proyectosInvestigacions;
    }




}


