package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProyectosInvestigacion generated by hbm2java
 */
public class ProyectosInvestigacion  implements java.io.Serializable {


     private int idProyectoInvestigacion;
     private LineaInvestigacion lineaInvestigacion;
     private String temaProyecto;
     private Set relProyectoInvestigadors = new HashSet(0);

    public ProyectosInvestigacion() {
    }

	
    public ProyectosInvestigacion(int idProyectoInvestigacion, String temaProyecto) {
        this.idProyectoInvestigacion = idProyectoInvestigacion;
        this.temaProyecto = temaProyecto;
    }
    public ProyectosInvestigacion(int idProyectoInvestigacion, LineaInvestigacion lineaInvestigacion, String temaProyecto, Set relProyectoInvestigadors) {
       this.idProyectoInvestigacion = idProyectoInvestigacion;
       this.lineaInvestigacion = lineaInvestigacion;
       this.temaProyecto = temaProyecto;
       this.relProyectoInvestigadors = relProyectoInvestigadors;
    }
   
    public int getIdProyectoInvestigacion() {
        return this.idProyectoInvestigacion;
    }
    
    public void setIdProyectoInvestigacion(int idProyectoInvestigacion) {
        this.idProyectoInvestigacion = idProyectoInvestigacion;
    }
    public LineaInvestigacion getLineaInvestigacion() {
        return this.lineaInvestigacion;
    }
    
    public void setLineaInvestigacion(LineaInvestigacion lineaInvestigacion) {
        this.lineaInvestigacion = lineaInvestigacion;
    }
    public String getTemaProyecto() {
        return this.temaProyecto;
    }
    
    public void setTemaProyecto(String temaProyecto) {
        this.temaProyecto = temaProyecto;
    }
    public Set getRelProyectoInvestigadors() {
        return this.relProyectoInvestigadors;
    }
    
    public void setRelProyectoInvestigadors(Set relProyectoInvestigadors) {
        this.relProyectoInvestigadors = relProyectoInvestigadors;
    }




}


