package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelAreaInteresInvestigador generated by hbm2java
 */
public class RelAreaInteresInvestigador  implements java.io.Serializable {


     private RelAreaInteresInvestigadorId id;
     private AreaInteres areaInteres;
     private Investigador investigador;

    public RelAreaInteresInvestigador() {
    }

    public RelAreaInteresInvestigador(RelAreaInteresInvestigadorId id, AreaInteres areaInteres, Investigador investigador) {
       this.id = id;
       this.areaInteres = areaInteres;
       this.investigador = investigador;
    }
   
    public RelAreaInteresInvestigadorId getId() {
        return this.id;
    }
    
    public void setId(RelAreaInteresInvestigadorId id) {
        this.id = id;
    }
    public AreaInteres getAreaInteres() {
        return this.areaInteres;
    }
    
    public void setAreaInteres(AreaInteres areaInteres) {
        this.areaInteres = areaInteres;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }




}


