package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelCentroInvGrupoAcId generated by hbm2java
 */
public class RelCentroInvGrupoAcId  implements java.io.Serializable {


     private int idCentroInvestigacion;
     private int idGrupoAcademico;

    public RelCentroInvGrupoAcId() {
    }

    public RelCentroInvGrupoAcId(int idCentroInvestigacion, int idGrupoAcademico) {
       this.idCentroInvestigacion = idCentroInvestigacion;
       this.idGrupoAcademico = idGrupoAcademico;
    }
   
    public int getIdCentroInvestigacion() {
        return this.idCentroInvestigacion;
    }
    
    public void setIdCentroInvestigacion(int idCentroInvestigacion) {
        this.idCentroInvestigacion = idCentroInvestigacion;
    }
    public int getIdGrupoAcademico() {
        return this.idGrupoAcademico;
    }
    
    public void setIdGrupoAcademico(int idGrupoAcademico) {
        this.idGrupoAcademico = idGrupoAcademico;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelCentroInvGrupoAcId) ) return false;
		 RelCentroInvGrupoAcId castOther = ( RelCentroInvGrupoAcId ) other; 
         
		 return (this.getIdCentroInvestigacion()==castOther.getIdCentroInvestigacion())
 && (this.getIdGrupoAcademico()==castOther.getIdGrupoAcademico());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCentroInvestigacion();
         result = 37 * result + this.getIdGrupoAcademico();
         return result;
   }   


}


