package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelCentroInvGrupoAc generated by hbm2java
 */
public class RelCentroInvGrupoAc  implements java.io.Serializable {


     private RelCentroInvGrupoAcId id;
     private CentroInvestigacion centroInvestigacion;
     private GrupoAcademico grupoAcademico;

    public RelCentroInvGrupoAc() {
    }

    public RelCentroInvGrupoAc(RelCentroInvGrupoAcId id, CentroInvestigacion centroInvestigacion, GrupoAcademico grupoAcademico) {
       this.id = id;
       this.centroInvestigacion = centroInvestigacion;
       this.grupoAcademico = grupoAcademico;
    }
   
    public RelCentroInvGrupoAcId getId() {
        return this.id;
    }
    
    public void setId(RelCentroInvGrupoAcId id) {
        this.id = id;
    }
    public CentroInvestigacion getCentroInvestigacion() {
        return this.centroInvestigacion;
    }
    
    public void setCentroInvestigacion(CentroInvestigacion centroInvestigacion) {
        this.centroInvestigacion = centroInvestigacion;
    }
    public GrupoAcademico getGrupoAcademico() {
        return this.grupoAcademico;
    }
    
    public void setGrupoAcademico(GrupoAcademico grupoAcademico) {
        this.grupoAcademico = grupoAcademico;
    }




}


