package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelGrupoAcLineaInv generated by hbm2java
 */
public class RelGrupoAcLineaInv  implements java.io.Serializable {


     private RelGrupoAcLineaInvId id;
     private GrupoAcademico grupoAcademico;
     private LineaInvestigacion lineaInvestigacion;

    public RelGrupoAcLineaInv() {
    }

    public RelGrupoAcLineaInv(RelGrupoAcLineaInvId id, GrupoAcademico grupoAcademico, LineaInvestigacion lineaInvestigacion) {
       this.id = id;
       this.grupoAcademico = grupoAcademico;
       this.lineaInvestigacion = lineaInvestigacion;
    }
   
    public RelGrupoAcLineaInvId getId() {
        return this.id;
    }
    
    public void setId(RelGrupoAcLineaInvId id) {
        this.id = id;
    }
    public GrupoAcademico getGrupoAcademico() {
        return this.grupoAcademico;
    }
    
    public void setGrupoAcademico(GrupoAcademico grupoAcademico) {
        this.grupoAcademico = grupoAcademico;
    }
    public LineaInvestigacion getLineaInvestigacion() {
        return this.lineaInvestigacion;
    }
    
    public void setLineaInvestigacion(LineaInvestigacion lineaInvestigacion) {
        this.lineaInvestigacion = lineaInvestigacion;
    }




}


