package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelGrupoAcLineaInvId generated by hbm2java
 */
public class RelGrupoAcLineaInvId  implements java.io.Serializable {


     private int idGrupoAcademico;
     private int idLineaInvestigacion;

    public RelGrupoAcLineaInvId() {
    }

    public RelGrupoAcLineaInvId(int idGrupoAcademico, int idLineaInvestigacion) {
       this.idGrupoAcademico = idGrupoAcademico;
       this.idLineaInvestigacion = idLineaInvestigacion;
    }
   
    public int getIdGrupoAcademico() {
        return this.idGrupoAcademico;
    }
    
    public void setIdGrupoAcademico(int idGrupoAcademico) {
        this.idGrupoAcademico = idGrupoAcademico;
    }
    public int getIdLineaInvestigacion() {
        return this.idLineaInvestigacion;
    }
    
    public void setIdLineaInvestigacion(int idLineaInvestigacion) {
        this.idLineaInvestigacion = idLineaInvestigacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelGrupoAcLineaInvId) ) return false;
		 RelGrupoAcLineaInvId castOther = ( RelGrupoAcLineaInvId ) other; 
         
		 return (this.getIdGrupoAcademico()==castOther.getIdGrupoAcademico())
 && (this.getIdLineaInvestigacion()==castOther.getIdLineaInvestigacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGrupoAcademico();
         result = 37 * result + this.getIdLineaInvestigacion();
         return result;
   }   


}


