package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelInvestigadorLineaGrupoId generated by hbm2java
 */
public class RelInvestigadorLineaGrupoId  implements java.io.Serializable {


     private int idInvestigador;
     private int idLineaInvestigacion;

    public RelInvestigadorLineaGrupoId() {
    }

    public RelInvestigadorLineaGrupoId(int idInvestigador, int idLineaInvestigacion) {
       this.idInvestigador = idInvestigador;
       this.idLineaInvestigacion = idLineaInvestigacion;
    }
   
    public int getIdInvestigador() {
        return this.idInvestigador;
    }
    
    public void setIdInvestigador(int idInvestigador) {
        this.idInvestigador = idInvestigador;
    }
    public int getIdLineaInvestigacion() {
        return this.idLineaInvestigacion;
    }
    
    public void setIdLineaInvestigacion(int idLineaInvestigacion) {
        this.idLineaInvestigacion = idLineaInvestigacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelInvestigadorLineaGrupoId) ) return false;
		 RelInvestigadorLineaGrupoId castOther = ( RelInvestigadorLineaGrupoId ) other; 
         
		 return (this.getIdInvestigador()==castOther.getIdInvestigador())
 && (this.getIdLineaInvestigacion()==castOther.getIdLineaInvestigacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdInvestigador();
         result = 37 * result + this.getIdLineaInvestigacion();
         return result;
   }   


}


