package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelInvestigadorLineaGrupo generated by hbm2java
 */
public class RelInvestigadorLineaGrupo  implements java.io.Serializable {


     private RelInvestigadorLineaGrupoId id;
     private Investigador investigador;
     private LineaInvestigacion lineaInvestigacion;

    public RelInvestigadorLineaGrupo() {
    }

    public RelInvestigadorLineaGrupo(RelInvestigadorLineaGrupoId id, Investigador investigador, LineaInvestigacion lineaInvestigacion) {
       this.id = id;
       this.investigador = investigador;
       this.lineaInvestigacion = lineaInvestigacion;
    }
   
    public RelInvestigadorLineaGrupoId getId() {
        return this.id;
    }
    
    public void setId(RelInvestigadorLineaGrupoId id) {
        this.id = id;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }
    public LineaInvestigacion getLineaInvestigacion() {
        return this.lineaInvestigacion;
    }
    
    public void setLineaInvestigacion(LineaInvestigacion lineaInvestigacion) {
        this.lineaInvestigacion = lineaInvestigacion;
    }




}


