package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelProyectoInvestigadorId generated by hbm2java
 */
public class RelProyectoInvestigadorId  implements java.io.Serializable {


     private Integer idInvestigador;
     private Integer idProyectoInvestigacion;

    public RelProyectoInvestigadorId() {
    }

    public RelProyectoInvestigadorId(Integer idInvestigador, Integer idProyectoInvestigacion) {
       this.idInvestigador = idInvestigador;
       this.idProyectoInvestigacion = idProyectoInvestigacion;
    }
   
    public Integer getIdInvestigador() {
        return this.idInvestigador;
    }
    
    public void setIdInvestigador(Integer idInvestigador) {
        this.idInvestigador = idInvestigador;
    }
    public Integer getIdProyectoInvestigacion() {
        return this.idProyectoInvestigacion;
    }
    
    public void setIdProyectoInvestigacion(Integer idProyectoInvestigacion) {
        this.idProyectoInvestigacion = idProyectoInvestigacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelProyectoInvestigadorId) ) return false;
		 RelProyectoInvestigadorId castOther = ( RelProyectoInvestigadorId ) other; 
         
		 return ( (this.getIdInvestigador()==castOther.getIdInvestigador()) || ( this.getIdInvestigador()!=null && castOther.getIdInvestigador()!=null && this.getIdInvestigador().equals(castOther.getIdInvestigador()) ) )
 && ( (this.getIdProyectoInvestigacion()==castOther.getIdProyectoInvestigacion()) || ( this.getIdProyectoInvestigacion()!=null && castOther.getIdProyectoInvestigacion()!=null && this.getIdProyectoInvestigacion().equals(castOther.getIdProyectoInvestigacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdInvestigador() == null ? 0 : this.getIdInvestigador().hashCode() );
         result = 37 * result + ( getIdProyectoInvestigacion() == null ? 0 : this.getIdProyectoInvestigacion().hashCode() );
         return result;
   }   


}


