package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * RelProyectoInvestigador generated by hbm2java
 */
public class RelProyectoInvestigador  implements java.io.Serializable {


     private RelProyectoInvestigadorId id;
     private Investigador investigador;
     private ProyectosInvestigacion proyectosInvestigacion;

    public RelProyectoInvestigador() {
    }

	
    public RelProyectoInvestigador(RelProyectoInvestigadorId id) {
        this.id = id;
    }
    public RelProyectoInvestigador(RelProyectoInvestigadorId id, Investigador investigador, ProyectosInvestigacion proyectosInvestigacion) {
       this.id = id;
       this.investigador = investigador;
       this.proyectosInvestigacion = proyectosInvestigacion;
    }
   
    public RelProyectoInvestigadorId getId() {
        return this.id;
    }
    
    public void setId(RelProyectoInvestigadorId id) {
        this.id = id;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }
    public ProyectosInvestigacion getProyectosInvestigacion() {
        return this.proyectosInvestigacion;
    }
    
    public void setProyectosInvestigacion(ProyectosInvestigacion proyectosInvestigacion) {
        this.proyectosInvestigacion = proyectosInvestigacion;
    }




}


