package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:04:36 PM by Hibernate Tools 4.3.1



/**
 * RelProyectoLinea generated by hbm2java
 */
public class RelProyectoLinea  implements java.io.Serializable {


     private RelProyectoLineaId id;
     private LineaInvestigacion lineaInvestigacion;
     private ProyectosInvestigacion proyectosInvestigacion;

    public RelProyectoLinea() {
    }

	
    public RelProyectoLinea(RelProyectoLineaId id) {
        this.id = id;
    }
    public RelProyectoLinea(RelProyectoLineaId id, LineaInvestigacion lineaInvestigacion, ProyectosInvestigacion proyectosInvestigacion) {
       this.id = id;
       this.lineaInvestigacion = lineaInvestigacion;
       this.proyectosInvestigacion = proyectosInvestigacion;
    }
   
    public RelProyectoLineaId getId() {
        return this.id;
    }
    
    public void setId(RelProyectoLineaId id) {
        this.id = id;
    }
    public LineaInvestigacion getLineaInvestigacion() {
        return this.lineaInvestigacion;
    }
    
    public void setLineaInvestigacion(LineaInvestigacion lineaInvestigacion) {
        this.lineaInvestigacion = lineaInvestigacion;
    }
    public ProyectosInvestigacion getProyectosInvestigacion() {
        return this.proyectosInvestigacion;
    }
    
    public void setProyectosInvestigacion(ProyectosInvestigacion proyectosInvestigacion) {
        this.proyectosInvestigacion = proyectosInvestigacion;
    }




}


