package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1



/**
 * Tesista generated by hbm2java
 */
public class Tesista  implements java.io.Serializable {


     private int idTesista;
     private Investigador investigador;
      private ProyectosInvestigacion proyectosInvestigacion;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;

    public Tesista() {
    }

	
    public Tesista(int idTesista, Investigador investigador, String nombre, String apellidoPaterno) {
        this.idTesista = idTesista;
        this.investigador = investigador;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
    }

    public Tesista(int idTesista, Investigador investigador, ProyectosInvestigacion proyectosInvestigacion, String nombre, String apellidoPaterno, String apellidoMaterno) {
        this.idTesista = idTesista;
        this.investigador = investigador;
        this.proyectosInvestigacion = proyectosInvestigacion;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
    }
   
   
    public int getIdTesista() {
        return this.idTesista;
    }
    
    public void setIdTesista(int idTesista) {
        this.idTesista = idTesista;
    }
    public Investigador getInvestigador() {
        return this.investigador;
    }
    
    public void setInvestigador(Investigador investigador) {
        this.investigador = investigador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    public ProyectosInvestigacion getProyectosInvestigacion() {
        return proyectosInvestigacion;
    }

    public void setProyectosInvestigacion(ProyectosInvestigacion proyectosInvestigacion) {
        this.proyectosInvestigacion = proyectosInvestigacion;
    }




}


