package me.carlosaguilar.gepin.model;
// Generated 7/04/2022 05:11:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private CentroInvestigacion centroInvestigacion;
     private Perfil perfil;
     private String password;
     private Date fechaAlta;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private int idEstatus;

    public Usuario() {
    }

    public Usuario(String idUsuario, CentroInvestigacion centroInvestigacion, Perfil perfil, String password, Date fechaAlta, String nombre, String apellidoPaterno, String apellidoMaterno, int idEstatus) {
       this.idUsuario = idUsuario;
       this.centroInvestigacion = centroInvestigacion;
       this.perfil = perfil;
       this.password = password;
       this.fechaAlta = fechaAlta;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.idEstatus = idEstatus;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public CentroInvestigacion getCentroInvestigacion() {
        return this.centroInvestigacion;
    }
    
    public void setCentroInvestigacion(CentroInvestigacion centroInvestigacion) {
        this.centroInvestigacion = centroInvestigacion;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public int getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(int idEstatus) {
        this.idEstatus = idEstatus;
    }




}


